<a href="https://colab.research.google.com/github/Nore-gibhub/Challenge3_TelecomX_part2/blob/main/challenge3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import pandas as pd

In [111]:
#Estos datos provienen del Challenge2 y corresponde a los datos tratados que quedaron en df_long
df_datos = pd.read_csv('/content/datos_TelecomX_tratados.csv')
df_datos

,customerID,Churn,customer_gender,customer_SeniorCitizen,customer_Partner,customer_Dependents,customer_tenure,account_Contract,account_PaperlessBilling,account_PaymentMethod,account_Charges.Monthly,account_Charges.Total,tipo_de_servicio,valor
0,0002-ORFBO,No,Female,0,Yes,Yes,9,One year,Yes,Mailed check,65.60,593.30,phone_PhoneService,Yes
1,0003-MKNFE,No,Male,0,No,No,9,Month-to-month,No,Mailed check,59.90,542.40,phone_PhoneService,Yes
2,0004-TLHLJ,Yes,Male,0,No,No,4,Month-to-month,Yes,Electronic check,73.90,280.85,phone_PhoneService,Yes
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Month-to-month,Yes,Electronic check,98.00,1237.85,phone_PhoneService,Yes
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Month-to-month,Yes,Mailed check,83.90,267.40,phone_PhoneService,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63382,9987-LUTYD,No,Female,0,No,No,13,One year,No,Mailed check,55.15,742.90,internet_StreamingMovies,No
63383,9992-RRAMN,Yes,Male,0,Yes,No,22,Month-to-month,Yes,Electronic check,85.10,1873.70,internet_StreamingMovies,Yes
63384,9992-UJOEL,No,Male,0,No,No,2,Month-to-month,Yes,Mailed check,50.30,92.75,internet_StreamingMovies,No
63385,9993-LHIEB,No,Male,0,Yes,Yes,67,Two year,No,Mailed check,67.85,4627.65,internet_StreamingMovies,Yes
63386,9995-HOTOH,No,Male,0,Yes,Yes,63,Two year,No,Electronic check,59.00,3707.60,internet_StreamingMovies,Yes

In [112]:
df_datos.shape

(63387, 14)

In [113]:
df_datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63387 entries, 0 to 63386
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customerID                63387 non-null  object
 1   Churn                     63387 non-null  object
 2   customer_gender           63387 non-null  object
 3   customer_SeniorCitizen    63387 non-null  int64
 4   customer_Partner          63387 non-null  object
 5   customer_Dependents       63387 non-null  object
 6   customer_tenure           63387 non-null  int64
 7   account_Contract          63387 non-null  object
 8   account_PaperlessBilling  63387 non-null  object
 9   account_PaymentMethod     63387 non-null  object
 10  account_Charges.Monthly   63387 non-null  float64
 11  account_Charges.Total     63387 non-null  float64
 12  tipo_de_servicio          63387 non-null  object
 13  valor                     63387 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 6.8+ MB

**Objetivos del Desafío**

*  Preparar los datos para el modelado (tratamiento, codificación, normalización).

*  Realizar análisis de correlación y selección de variables.

*  Entrenar dos o más modelos de clasificación.

*  Evaluar el rendimiento de los modelos con métricas.

*  Interpretar los resultados, incluyendo la importancia de las variables.

*  Crear una conclusión estratégica señalando los principales factores que influyen en la cancelación.

**Lo que vas a practicar**

*  Preprocesamiento de datos para Machine Learning
*  Construcción y evaluación de modelos predictivos
*  Interpretación de resultados y entrega de insights
*  Comunicación técnica con enfoque estratégico

##**Tratamiento de los Datos**

In [114]:
#Eliminando Columnas que no aportan Valor

df_datos.drop(['customerID','account_PaperlessBilling','account_PaymentMethod','valor'],axis=1,inplace=True)
df_datos.head()

,Churn,customer_gender,customer_SeniorCitizen,customer_Partner,customer_Dependents,customer_tenure,account_Contract,account_Charges.Monthly,account_Charges.Total,tipo_de_servicio
0,No,Female,0,Yes,Yes,9,One year,65.6,593.30,phone_PhoneService
1,No,Male,0,No,No,9,Month-to-month,59.9,542.40,phone_PhoneService
2,Yes,Male,0,No,No,4,Month-to-month,73.9,280.85,phone_PhoneService
3,Yes,Male,1,Yes,No,13,Month-to-month,98.0,1237.85,phone_PhoneService
4,Yes,Female,1,Yes,No,3,Month-to-month,83.9,267.40,phone_PhoneService

In [115]:
import warnings
warnings.filterwarnings('ignore')

In [116]:
#Encoding - Transformando variables categóricas a formato númerico

df_datos['Churn'] = df_datos['Churn'].replace({'No':0,'Yes':1})
df_datos['customer_gender'] = df_datos['customer_gender'].replace({'Male':0,'Female':1})
df_datos['customer_Partner'] = df_datos['customer_Partner'].replace({'No':0,'Yes':1})
df_datos['customer_Dependents'] = df_datos['customer_Dependents'].replace({'No':0,'Yes':1})
df_datos

,Churn,customer_gender,customer_SeniorCitizen,customer_Partner,customer_Dependents,customer_tenure,account_Contract,account_Charges.Monthly,account_Charges.Total,tipo_de_servicio
0,0,1,0,1,1,9,One year,65.60,593.30,phone_PhoneService
1,0,0,0,0,0,9,Month-to-month,59.90,542.40,phone_PhoneService
2,1,0,0,0,0,4,Month-to-month,73.90,280.85,phone_PhoneService
3,1,0,1,1,0,13,Month-to-month,98.00,1237.85,phone_PhoneService
4,1,1,1,1,0,3,Month-to-month,83.90,267.40,phone_PhoneService
...,...,...,...,...,...,...,...,...,...,...
63382,0,1,0,0,0,13,One year,55.15,742.90,internet_StreamingMovies
63383,1,0,0,1,0,22,Month-to-month,85.10,1873.70,internet_StreamingMovies
63384,0,0,0,0,0,2,Month-to-month,50.30,92.75,internet_StreamingMovies
63385,0,0,0,1,1,67,Two year,67.85,4627.65,internet_StreamingMovies
63386,0,0,0,1,1,63,Two year,59.00,3707.60,internet_StreamingMovies

In [117]:
#Encoding - Transformando variables categóricas a formato númerico

categoricas = ['account_Contract','tipo_de_servicio']
datos_codif = pd.get_dummies(data=df_datos,columns=categoricas,dtype=int).head()
datos_codif

,Churn,customer_gender,customer_SeniorCitizen,customer_Partner,customer_Dependents,customer_tenure,account_Charges.Monthly,account_Charges.Total,account_Contract_Month-to-month,account_Contract_One year,account_Contract_Two year,tipo_de_servicio_internet_DeviceProtection,tipo_de_servicio_internet_InternetService,tipo_de_servicio_internet_OnlineBackup,tipo_de_servicio_internet_OnlineSecurity,tipo_de_servicio_internet_StreamingMovies,tipo_de_servicio_internet_StreamingTV,tipo_de_servicio_internet_TechSupport,tipo_de_servicio_phone_MultipleLines,tipo_de_servicio_phone_PhoneService
0,0,1,0,1,1,9,65.6,593.30,0,1,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,9,59.9,542.40,1,0,0,0,0,0,0,0,0,0,0,1
2,1,0,0,0,0,4,73.9,280.85,1,0,0,0,0,0,0,0,0,0,0,1
3,1,0,1,1,0,13,98.0,1237.85,1,0,0,0,0,0,0,0,0,0,0,1
4,1,1,1,1,0,3,83.9,267.40,1,0,0,0,0,0,0,0,0,0,0,1

In [118]:
#Verificación de la Proporción de Cancelación (Churn)

Dist_Churn = datos_codif.Churn.value_counts()
Dist_Churn

Churn
1    3
0    2
Name: count, dtype: int64

##**Análisis de correlación**













Visualiza la matriz de correlación para identificar relaciones entre las variables numéricas. Presta especial atención a las variables que muestran una mayor correlación con la cancelación, ya que estas pueden ser fuertes candidatas para el modelo predictivo.

##**Análisis dirigido**

Investiga cómo variables específicas se relacionan con la cancelación, tales como:

*  Tiempo de contrato × Cancelación

*  Gasto total × Cancelación

Utiliza gráficos como boxplots o scatter plots para visualizar patrones y posibles tendencias.

##**Separación de datos para Modelos Predictivos**

Divide el conjunto de datos en entrenamiento y prueba para evaluar el rendimiento del modelo. Una división común es 70% para entrenamiento y 30% para prueba, o 80/20, dependiendo del tamaño de la base de datos.Divide el conjunto de datos en entrenamiento y prueba para evaluar el rendimiento del modelo. Una división común es 70% para entrenamiento y 30% para prueba, o 80/20, dependiendo del tamaño de la base de datos.

##**Creación de Modelos Predictivos**

Crea al menos dos modelos diferentes para predecir la cancelación de clientes.

Un modelo puede requerir normalización, como Regresión Logística o KNN.

El otro modelo puede no requerir normalización, como Árbol de Decisión o Random Forest.

La decisión de aplicar o no la normalización depende de los modelos seleccionados. Ambos modelos pueden ser creados sin normalización, pero también es una opción combinar modelos con y sin normalización.

*Justificación:*

Regresión Logística / KNN: Estos modelos son sensibles a la escala de los datos, por lo que la normalización es importante para que los coeficientes o las distancias se calculen correctamente.

Árbol de Decisión / Random Forest: Estos modelos no dependen de la escala de los datos, por lo que no es necesario aplicar normalización.

Si decides normalizar los datos, deberías explicar cómo esta etapa asegura que los modelos basados en distancia o en optimización de parámetros no se vean sesgados por la magnitud de las variables.

##**Evaluación de los Modelos**

Evalúa cada modelo utilizando las siguientes métricas:

Exactitud (Acurácia)

Precisión

Recall

F1-score

Matriz de confusión

Después, realiza un análisis crítico y compara los modelos:

¿Cuál modelo tuvo el mejor desempeño?

¿Algún modelo presentó overfitting o underfitting? Si es así, considera las posibles causas y ajustes:

Overfitting: Cuando el modelo aprende demasiado sobre los datos de entrenamiento, perdiendo la capacidad de generalizar a nuevos datos. Considera reducir la complejidad del modelo o aumentar los datos de entrenamiento.

Underfitting: Cuando el modelo no captura bien las tendencias de los datos, lo que indica que es demasiado simple. Intenta aumentar la complejidad del modelo o ajustar sus parámetros.

##**Análisis de la Importancia de las Variables**

Después de elegir los modelos, realiza el análisis de las variables más relevantes para la predicción de la cancelación:

Regresión Logística: Investiga los coeficientes de las variables, que muestran su contribución a la predicción de cancelación.

KNN (K-Nearest Neighbors): Observa cómo los vecinos más cercanos influyen en la decisión de clasificación. Las variables más impactantes pueden ser aquellas que más contribuyen a la proximidad entre los puntos de datos.

Random Forest: Utiliza la importancia de las variables proporcionada por el modelo. Random Forest calcula la importancia basándose en cómo cada variable contribuye a la reducción de la impureza durante las divisiones de los árboles.

SVM (Support Vector Machine): En el SVM, las variables más relevantes son aquellas que influyen en la frontera de decisión entre las clases. Puedes analizar los coeficientes de los vectores de soporte para entender qué variables tienen mayor impacto.

Otros Modelos: Dependiendo del modelo elegido, considera el análisis de métricas específicas para comprender la relevancia de las variables. Por ejemplo, coeficientes en modelos lineales, pesos en redes neuronales, o la importancia relativa en técnicas de boosting (como XGBoost).

#**INFORME FINAL**

Elaboren un informe detallado, destacando los factores que más influyen en la cancelación, basándose en las variables seleccionadas y en el rendimiento de cada modelo.

Identifiquen los principales factores que afectan la cancelación de clientes y propongan estrategias de retención basadas en los resultados obtenidos.